name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    container: gcc:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --fix-missing
          apt-get install -y -f
          apt-get install -y cmake libgtest-dev python3 python3-pip python3-venv python3.11-dev libc6-dev libffi-dev default-jre-headless openjdk-17-jre
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.30.0/allure-commandline-2.30.0.tgz
          tar -zxvf allure-commandline-2.30.0.tgz -C /opt/
          ln -s /opt/allure-2.30.0/bin/allure /usr/bin/allure
          allure --version
          rm allure-commandline-2.30.0.tgz
          cd /usr/src/gtest && cmake . && make && cp lib/*.a /usr/lib/
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          make
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
          retention-days: 7

  unit_tests:
    runs-on: ubuntu-latest
    container: gcc:latest
    needs: build_firmware
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --fix-missing
          apt-get install -y -f
          apt-get install -y cmake libgtest-dev python3 python3-pip python3-venv python3.11-dev libc6-dev libffi-dev default-jre-headless openjdk-17-jre
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.30.0/allure-commandline-2.30.0.tgz
          tar -zxvf allure-commandline-2.30.0.tgz -C /opt/
          ln -s /opt/allure-2.30.0/bin/allure /usr/bin/allure
          allure --version
          rm allure-commandline-2.30.0.tgz
          cd /usr/src/gtest && cmake . && make && cp lib/*.a /usr/lib/
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/
      - name: Set execute permissions
        run: chmod +x build/test_calculator
      - name: Run unit tests
        run: |
          cd build
          ./test_calculator --gtest_output=xml:test_results_gtest.xml
      - name: Generate Allure report for GTest
        run: |
          mkdir -p allure-results
          cp build/test_results_gtest.xml allure-results/
          allure generate allure-results -o allure-report-unit --clean
          ls -l allure-report-unit
      - name: Store test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: |
            build/test_results_gtest.xml
            allure-report-unit/
          retention-days: 7

  integration_tests:
    runs-on: ubuntu-latest
    container: gcc:latest
    needs: build_firmware
    steps:
      - uses: actions/checkout@v4
      - name: Verify files
        run: |
          ls -l  
          cat requirements.txt  
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake libgtest-dev python3 python3-pip python3-venv python3.11-dev libc6-dev libffi-dev openjdk-17-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure_2.30.0-1_all.deb
          dpkg -i allure_2.30.0-1_all.deb
          allure --version
          rm allure_2.30.0-1_all.deb
          python3 --version  
          python3 -m venv venv
          ls -l venv/bin  
          ./venv/bin/python -m ensurepip --upgrade
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/pip --version  
          ls -l requirements.txt 
          ./venv/bin/pip install -r requirements.txt --no-cache-dir --verbose 
          ls -l venv/bin  
          ./venv/bin/pip show pytest  
          cd /usr/src/gtest && cmake . && make && cp lib/*.a /usr/lib/
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/
      - name: Set execute permissions
        run: chmod +x build/libcalculator.so
      - name: Run integration tests
        run: |
          ls build/libcalculator.so
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./build
          ./venv/bin/pytest tests/integration/ --alluredir=allure-results --junitxml=test_results_pytest.xml
      - name: Generate Allure report for PyTest
        run: |
          allure generate allure-results -o allure-report-integration --clean
          ls -l allure-report-integration
      - name: Store test results
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: |
            test_results_pytest.xml
            allure-report-integration/
          retention-days: 7
